---
fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: ['--fix', 'lf']
      - id: check-json
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-merge-conflict
      - id: check-symlinks
  - repo: https://github.com/toddnguyen47/pre-commit-hooks
    rev: v1.1.0
    hooks:
      - id: convert-beginning-tabs
        args: ["--whitespaces-count", "2"] # defaults to 4 with no args
  - repo: local
    hooks:
      - id: run-pmd
        name: pmd java source code analyzer
        entry: python3 change/path/to/pre_commit_hooks/run_pmd.py
        language: python
        types: [java]
      - id: eclipse-formatter
        name: Run eclipse-formatter
        entry: ~/.pyenv/shims/python3 pre_commit_hooks/run_eclipse_java_format.py
        language: python
        types: [java]
        args: ["--ignore-files", "file1.java, file2.java"] # comma-separated list of files to ignore
