fail_fast: true
repos:
  - repo: https://github.com/PyCQA/pylint
    rev: v3.0.0-a4
    hooks:
      - id: pylint
        types: [python]
        args:
          - --max-line-length=120
          - --disable=too-few-public-methods
