fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: echo-virtualenv-warning
        name: Echo Virtualenv warning
        entry: echo "Remember to activate virtualenv before commit!"
        language: system
        verbose: true
        pass_filenames: false
      - id: generate-requirements-txt
        name: Generate requirements.txt
        entry: bash -c 'cd python/starter-python3-project && pipenv run pip3 freeze > requirements.txt'
        language: system
        pass_filenames: false
      - id: black
        name: black formatter
        entry: python3 python/starter-python3-project/pre_commit_hooks/run_black.py
        language: python
        types: [python] # types of files to run this hook on
      - id: flake8
        name: flake8
        entry: python3 python/starter-python3-project/pre_commit_hooks/run_flake8.py
        language: python
        types: [python] # types of files to run this hook on
      - id: pylint
        name: pylint
        entry: python3 python/starter-python3-project/pre_commit_hooks/run_pylint.py
        language: python
        types: [python] # types of files to run this hook on
