fail_fast: true
repos:
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pipenv run pylint
        language: system
        types: [python]
        args:
          - --max-line-length=120
          - --ignore-imports=yes
