fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: echo-virtualenv-warning
        name: Echo Virtualenv warning
        entry: echo "Remember to activate virtualenv before commit!"
        language: system
        verbose: true
        pass_filenames: false
      - id: black
        name: Format Python files using Black formatter
        entry: bash -c 'cd python/starter-python3-project && pre-commit-scripts/run-black.sh $@'
        language: system
        types: [python]
        args:
          - --line-length=120
      - id: pylint
        name: pylint
        entry: bash -c 'cd python/starter-python3-project && pre-commit-scripts/run-pylint.sh $@'
        language: system
        types: [python]
