---
fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: check-json
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-merge-conflict
      - id: check-symlinks
  - repo: https://github.com/toddnguyen47/pre-commit-hooks
    rev: v1.0.0
    hooks:
      - id: convert-beginning-tabs
        args: ["--whitespaces-count", "2"] # defaults to 4 with no args
  - repo: local
    hooks:
      - id: run-pmd
        name: pmd java source code analyzer
        entry: python3 java/starter-gradle/pre_commit_hooks/run_pmd.py
        language: python
        types: [java]
